### PR TITLE
Bump database schema version 

### PR DESCRIPTION
**Pull request by gfrn**
* Bump database schema version

* Drop old Python versions

* Update DB tarfile artifact reference

* Update Python version requirements in README

* Pin sqlacodegen version to 3.0.0rc5

* Update sqlacodegen command

Tests failed for one of the "generate ORM PR" actions, which I imagine is because it's duplicated (once for the push, and once for the pull request), part of having merged this from a forked repo

I am also not too sure of how well this might work with 1.4. SQLAlchemy 2.0 introduces a ton of breaking changes, and sqlacodegen 2 was making this way more painful than it had to be. Primarily because it has no support for SQLAlchemy 2.0 and all the new features it has.

3.0.0rc2 is the last (only?) version of sqlacodegen to "support" both 1.4 and 2.0, and even then, it fails if you follow their docs.

2.0.0 never really supported SQLAlchemy 2.0 (https://github.com/agronholm/sqlacodegen/blob/60392056b95a0665d4af67a8403eb998a92a5e7e/pyproject.toml)

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -21,7 +21,7 @@ as webservices.
 Please see https://ispyb.readthedocs.io.
 
 ### Requirements
-* Python 3.7, 3.8, 3.9, 3.10, 3.11
+* Python 3.7, 3.8, 3.9 (minimum), 3.10, 3.11, 3.12, 3.13 (recommended)
```
Comment (ndevenish) [inline README.md]:
```suggestion
* Python 3.10 (minimum), 3.11, 3.12, 3.13 (recommended)
```

**Review by ndevenish — CHANGES_REQUESTED** [review]
We should probably completely drop the python versions e.g. also change in https://github.com/DiamondLightSource/ispyb-api/pull/227/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R25. Otherwise looks okay, as long as it's doing what you need?

**Comment by ndevenish** [comment]
I'm left a little confused how this leaves the ispyb-api support for sqlalchemy<2. I don't really have any objection to dropping 1.4, as long as we don't have anything critical depending on it (or can get away with not having the latest schema while we update them).

I'm probably not against just dropping 1.4.

File: README.md (hunk 1 above)
Comment (gfrn) [reply README.md]: Ah yeah, good idea, I kept them as "minimums" in case someone at Diamond still used 3.7 in prod. But I think (hope?) this is not the case

**Comment by gfrn** [comment]
> I'm left a little confused how this leaves the ispyb-api support for sqlalchemy<2. I don't really have any objection to dropping 1.4, as long as we don't have anything critical depending on it (or can get away with not having the latest schema while we update them).
> 
> I'm probably not against just dropping 1.4.

I've tried it out with 1.4, and although you can kludge it into working, I wouldn't say it's supported. sqlacodegen itself doesn't support 1.4 anymore, and the generated code makes use of typed column declarations, which is the recommended way to go with 2. 1.4 doesn't support that without intermediaries.

I would say that this doesn't support 1.4, isn't intended to work with 1.4, and we can't reasonably provide two separate schemas, unfortunately. This is a breaking change, so I suggest we bump it up by a major version, and possibly release it as beta for the moment being

**Comment by ndevenish** [comment]
@gfrn 
```
        # Get child AutoProcScalingStatistics entries
>       stats = aps.AutoProcScalingStatistics
E       AttributeError: 'AutoProcScaling' object has no attribute 'AutoProcScalingStatistics'

tests/sqlalchemy/test_models.py:48: AttributeError
```
It looks like you've changed the way backreferences are generated here (Absolutely _not_ implying this was bad by asking, but what was the reason for this?), does this error make sense to you in relation to that?

**Review by ndevenish — APPROVED** [review]
